import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import { useRouter } from 'next/router'
import { PlusCircle } from 'react-icons/fa';
import NavBar from 'src/pages/components/navbar';

const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const router = useRouter()

  const { data: session } = useSession()

  const navigation = [
    { Icon: PlusCircle, href: '/addPost', current: router.pathname === '/addPost' },
  ];
  if (session) {
    router.push('/posts');
    return null;
  }

  return (
  <>
    
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <NavBar
      navigation={navigation}
      user={session?.user}
      onSignIn={signIn}
      onSignOut={signOut}
    />
    <main className={styles.main2}>
      <div className={styles.h_cnt}>
        <h1 className={styles.h_title}>
          Welcome to WorldBlog!
        </h1>
        <br />
        <div className={styles.h_bnt_cnt}>
      {session ? (
        <p>Signed in as {session.user.email}</p>
      ) : (
        <button className={styles.signin_bnt} onClick={() => signIn()}>Sign in</button>
      )}
      </div>
       </div>
    </main>
  </>
);

}
